name: DEV CICD Kubernetes

on:
  push:
    branches:
      - development-devops

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: "790730093083"
  AWS_OIDC_ROLE_NAME: "Github-action-cicd-role"
  ECR_REPOSITORY: 'dev/application-fe'
  SECRET_ID: 'dev/application/FE'
  PROFILE: "dev"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_DEV_ACCOUNT_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_ACCOUNT_SECRET_KEY }}
          aws-region: ap-south-1  

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2
          aws ecr get-login-password --region "${AWS_REGION}" \
            | docker login --username AWS --password-stdin  ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Fetch secrets from AWS Secrets Manager
        id: secrets
        run: |
          SECRET_JSON=$(aws secretsmanager get-secret-value \
            --secret-id "${{ env.SECRET_ID }}" \
            --region "${{ env.AWS_REGION }}" \
            --query SecretString \
            --output text)

          # Convert secret JSON to build args dynamically
          echo "BUILD_ARGS<<EOF" >> $GITHUB_ENV
          echo "$SECRET_JSON" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            profile=${{ env.PROFILE }}
            ${{ env.BUILD_ARGS }}
